config/routes.rb
Rails.application.routes.draw do
  resources :events do
  	resources :check_ins, only: [:index, :new]
  end
  resources :check_ins, only: [:create, :show, :edit, :update, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'events#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/check_in.rb
class CheckIn < ApplicationRecord
	belongs_to :event

	before_save { self.email = self.email.downcase } # should be ok not testing this
	validates :name, presence: true, length: { maximum: 50 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, 
					  length: { maximum: 255 },
					  format: { with: VALID_EMAIL_REGEX },
					  uniqueness: { case_sensitive: false, scope: :event_id }
	validates :event_id, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

end

app/models/event.rb
class Event < ApplicationRecord
	has_many :check_ins, dependent: :destroy
	accepts_nested_attributes_for :check_ins, allow_destroy: true
	validates :title, presence: true, length: { maximum: 255 } 
	validates :date, presence: true
	validates :creator, presence: true, length: { maximum: 50 }

	# ValidatesTimeliness gem
	validates_datetime :date, :on_or_after => :today
	

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

end

app/controllers/check_ins_controller.rb
class CheckInsController < ApplicationController
  before_action :set_check_in, only: [:show, :edit, :update, :destroy]

  # GET /check_ins
  # GET /check_ins.json
  def index
    @event = Event.find_by(params[:event_id])
    @check_ins = CheckIn.all.order(:created_at)
  end

  # GET /check_ins/1
  # GET /check_ins/1.json
  def show
  end

  # GET /check_ins/new
  def new
    @check_in = CheckIn.new
  end

  # GET /check_ins/1/edit
  def edit
  end

  # POST /check_ins
  # POST /check_ins.json
  def create
    @check_in = CheckIn.new(check_in_params)

    respond_to do |format|
      if @check_in.save
        format.html { redirect_to @check_in, notice: 'Check in was successfully created.' }
        format.json { render :show, status: :created, location: @check_in }
      else
        format.html { render :new }
        format.json { render json: @check_in.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /check_ins/1
  # PATCH/PUT /check_ins/1.json
  def update
    respond_to do |format|
      if @check_in.update(check_in_params)
        format.html { redirect_to @check_in, notice: 'Check in was successfully updated.' }
        format.json { render :show, status: :ok, location: @check_in }
      else
        format.html { render :edit }
        format.json { render json: @check_in.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /check_ins/1
  # DELETE /check_ins/1.json
  def destroy
    @check_in.destroy
    respond_to do |format|
      format.html { redirect_to check_ins_url, notice: 'Check in was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_check_in
      @check_in = CheckIn.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def check_in_params
      params.require(:check_in).permit(:name, :email, :event_id)
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all.order(:date)
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # GET events/1/check-ins
  # list attendeess for particular event

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:title, :date, :creator)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/check_ins_helper.rb
module CheckInsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/check_ins/_form.html.erb
<%= form_with(model: check_in, local: true) do |form| %>
  <% if check_in.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(check_in.errors.count, "error") %> prohibited this check_in from being saved:</h2>

      <ul>
      <% check_in.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :check_in_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :check_in_email %>
  </div>

  <div class="field">
    <%= form.label :event_id %>
    <%= form.collection_select(:event_id, Event.all, :id, :title) %>
  </div>

  <div class="actions">
    <%= form.submit :class => "button" %>
  </div>
<% end %>

app/views/check_ins/edit.html.erb
<h1>Editing Check In</h1>

<%= render 'form', check_in: @check_in %>

<%= link_to 'Back', event_check_ins_path(@check_in.event_id) %>

app/views/check_ins/index.html.erb
<p id="notice"><%= notice %></p>

<div class="center">
  <h1>Attendees for <%= Event.find_by(id: params[:event_id]).title %></h1>
</div>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Check In Time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @check_ins.each do |check_in| %>
      <% if check_in.event_id.to_s == params[:event_id].to_s %>
        <tr id=<%= check_in.id %>>
          <td><%= check_in.name %></td>
          <td><%= check_in.email %></td>
          <td><%= check_in.created_at.strftime("%B %d, %Y; %l:%M%p") %></td>
          <td><%= link_to 'Edit', edit_check_in_path(check_in) %></td>
          <td><%= link_to 'Destroy', check_in, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Back to All Events', events_path %> |
<%= link_to 'Check In', new_event_check_in_path(params[:event_id]) %>

app/views/check_ins/new.html.erb
<h1>New Check In</h1>

<%= render 'form', check_in: @check_in %>

<%= link_to 'Back to All Events', events_path %>

app/views/check_ins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @check_in.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @check_in.email %>
</p>

<p>
  <strong>Event:</strong>
  <%= Event.find_by(id: @check_in.event_id).title %>
</p>

<p>
	<strong> Check In Time:</strong>
	<%= @check_in.created_at.strftime("%B %d, %Y; %l:%M%p") %>
</p>

<%= link_to 'Edit', edit_check_in_path(@check_in) %> |
<%= link_to 'Back', event_check_ins_path(@check_in.event_id) %>

app/views/events/_form.html.erb
<%= form_with(model: event, local: true) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :event_title %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.datetime_select :date, id: :event_date %>
  </div>

  <div class="field">
    <%= form.label :creator %>
    <%= form.text_field :creator, id: :event_creator %>
  </div>

  <div class="actions">
    <%= form.submit :class => "button" %>
  </div>
<% end %>

app/views/events/check_in.html.erb
<h1>Checking In</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back to All Events', events_path %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<div class="center">
  <h1> <%= image_tag("swirl.gif", alt: "Swirl 1", width: 80, height: 40) %>
  Events
  <%= image_tag("swirl.gif", alt: "Swirl 2", width: 80, height: 40) %>
  </h1>
</div>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Title</th>
      <th>Date</th>
      <th>Time</th>
      <th>Creator</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr id=<%= "#{event.id}"%>>
        <td><%= event.title %></td>
        <td><%= event.date.strftime("%B %d, %Y") %></td>
        <td><%= event.date.strftime("%l:%M %p") %></td>
        <td><%= event.creator %></td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @event.title %>
</p>

<p>
  <strong>Date:</strong>
  <%= @event.date.strftime("%B %d, %Y") %>
</p>

<p>
	<strong>Time:</strong>
	<%= @event.date.strftime("%l:%M%p") %>
</p>

<p>
  <strong>Creator:</strong>
  <%= @event.creator %>
</p>

<%= link_to 'Back to All Events', events_path %> |
<%= link_to 'Attendees', event_check_ins_path(@event) %> |
<%= link_to 'Check In', new_event_check_in_path(@event) %> |
<%= link_to 'Edit Event', edit_event_path(@event) %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    SDMP Final Project, by Anna Craven
  </small>

<%= link_to image_tag("raven.jpg", alt: "Raven", width: 30, height: 30), 'https://www.poetryfoundation.org/poems/48860/the-raven' %>

</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Event Registration System</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>

  <%= render 'layouts/footer' %>
</html>